name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  PR_NUMBER: '${{ github.event.number }}'
  SOURCE_BRANCH: $GITHUB_HEAD_REF
  FIXER_BRANCH: auto-fixed/$GITHUB_HEAD_REF
  TITLE: Apply fixes from JS-CS-Fixer
  DESCRIPTION: This merge request applies JS code style fixes from an analysis carried out through GitHub Actions.

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun --bun run lint

  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Typecheck
        run: bun --bun run typecheck

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Unit Test
        run: bun test

  js-cs-fixer:
    runs-on: ubuntu-latest

    if: github.event_name == 'pull_request' && ! startsWith(github.ref, 'refs/heads/auto-fixed/')

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Prepare Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "action@github.com"
          git checkout -B "${{ env.FIXER_BRANCH }}"

      - name: Apply auto-fixers
        run: bun run lint:fix

      - name: Create Fixer PR
        run: |
          if [[ -z $(git status --porcelain) ]]; then
            echo "Nothing to fix... Exiting."
            exit 0
          fi
          OPEN_PRS=`curl --silent -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls?state=open"`
          OPEN_FIXER_PRS=`echo ${OPEN_PRS} | grep -o "\"ref\": \"${{ env.FIXER_BRANCH }}\"" | wc -l`
          git commit -am "${{ env.TITLE }}"
          git push origin "${{ env.FIXER_BRANCH }}" --force
          if [ ${OPEN_FIXER_PRS} -eq "0" ]; then
            curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls" \
              -d "{ \"head\":\"${{ env.FIXER_BRANCH }}\", \"base\":\"${{ env.SOURCE_BRANCH }}\", \"title\":\"${{ env.TITLE }}\", \"body\":\"${{ env.DESCRIPTION }}\n\nTriggered by #${{ env.PR_NUMBER }}\" }"
          fi
          exit 1
